### ISSUE TITLE
Pocket both red & orange on first hit

### ISSUE THREAD

**Issue by iisurge** [turbomaze/elliptical-pool#1]
If you pocket orange and red on the first hit the game continues if player 1's color went in first and tells player 2 to get the black in

**Comment by turbomaze** [comment]
You made two at once?! Man oh man this bug is a pain in the butt to reproduce, haha. Let me clarify what you're saying because I think it might be an intended feature:
1. Game begins. Player 1 is ORANGE, Player 2 is RED.
2. Player 1 shoots the cue ball and ORANGE goes in.
3. ? Instructions tell Player 1 to pocket BLACK.
4. In the same turn, RED goes in.
5. ? Instructions notify Player 1 that they scored their opponent's ball.
6. Balls stop moving.
7. Instructions tell Player 2 to score black.

If steps 3 and 5 happened, then this is an intended feature. I've always played pool treating shooting your opponent's ball as a foul/mistake, losing you your turn. Can you confirm steps 1-7? BTW in trying to score two at once, I think I may have found another bug...

**Comment by iisurge** [comment]
Nope, it goes directly from, Player 1, try to pocket black to, Player 2, try to pocket black, it never informs that they scored the oponets ball, I found a spot on the board to reproduce this, ill download a screen recorder and take a video

**Comment by turbomaze** [comment]
Alright. I've managed to make the correct color and then black on the first turn, and have confirmed a bug that prevents the game from ever finishing. I imagine the bug you've reported has a similar cause. I'm going to try and just follow the execution of the program to find the logic error because it's really difficult to repeat!

**Comment by iisurge** [comment]
this is what happens, it didn't record my mouse so might be hard to reproduce for you still: https://www.youtube.com/watch?v=r4s7beAnpN8

**Comment by turbomaze** [comment]
Thank you for the video. I am in awe that you can consistently make two at a time... I'm going add slight randomness, perhaps via friction, to prevent this kind of wizardry! I'll work on the bug.

**Comment by iisurge** [comment]
Yea would make it interesting, i also found a place to hit orange in the first shot every time. BTW, thanks for making this, I saw the video and had hoped someone did so I looked here

**Comment by turbomaze** [comment]
I'm glad to have been that someone, haha. I am confident I've fixed this bug with commit f0f051e. It's uploaded on the game page. Can you confirm this fixes this issue?

**Comment by iisurge** [comment]
Works as you said it should now, thanks!
